CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  openid VARCHAR(128) DEFAULT NULL,
  display_name VARCHAR(128) NOT NULL,
  avatar_url VARCHAR(255) NOT NULL DEFAULT '',
  mobile VARCHAR(32) DEFAULT NULL,
  email VARCHAR(128) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_users_username (username),
  UNIQUE KEY uk_users_openid (openid),
  UNIQUE KEY uk_users_mobile (mobile),
  UNIQUE KEY uk_users_email (email)
);

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_roles_code (code)
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT UNSIGNED NOT NULL,
  role_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS auth_identities (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  identity_type VARCHAR(32) NOT NULL,
  identifier VARCHAR(128) NOT NULL,
  credential VARCHAR(255) NOT NULL DEFAULT '',
  extra TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_identity_type_identifier (identity_type, identifier),
  KEY idx_auth_identities_user_id (user_id)
);

CREATE TABLE IF NOT EXISTS oauth_clients (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  client_id VARCHAR(64) NOT NULL,
  client_secret VARCHAR(128) NOT NULL,
  name VARCHAR(128) NOT NULL,
  code VARCHAR(64) NOT NULL DEFAULT '',
  response_type VARCHAR(32) NOT NULL DEFAULT 'code',
  redirect_uri VARCHAR(255) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_oauth_clients_client_id (client_id)
);
